export default function Descriptions() {
    return(
        <div>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
            <h1>Descriptions</h1>
        </div>
    )
}